pipeline {
     agent any

     environment {
         IMAGE = "globalmedicare-frontend"
         TAG = "latest"
         REGISTRY = "docker.io/arshabk"
     }
     stages {
         stage('Clone') {
             steps {
                 git branch: 'feature/frontend', url: 'https://github.com/arshaprajesh/medicare_frontend.git'
                 echo 'Repository cloned'

             }
         }
         stage('Build frontend') {
             steps {
                 dir('globalmedicare-app') {
                     sh 'npm install'
                     sh 'npm run build'
                     echo 'JAR built successfully.'
                 }
             }
         }
         stage('Docker build'){
             steps {
                 dir('globalmedicare-app') {
                     sh 'docker build -t $REGISTRY/$IMAGE:$TAG .'
                     echo 'image successfully created.'
                 }
             }
         }
         stage('Docker push'){
             steps {
                 withCredentials([usernamePassword(credentialsId: 'dockerhub_creds',
                 usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                 sh 'echo $PASS | docker login -u $USER --password-stdin'
                 sh 'docker push $REGISTRY/$IMAGE:$TAG'

                 echo 'login successfully.'
                 }

             }
         }
         stage('deploy to kubernetes'){
             steps {
                 dir('globalmedicare-app') {
                      sh 'kubectl apply -f k8s/frontend-deployment.yaml'
                      sh 'kubectl apply -f k8s/frontend-service.yaml'
                      echo ' successfully deployed'
                 }
             }
         }
     }
}